### ISSUE TITLE
Addition SHAP importance

### ISSUE THREAD

**Issue by valots12** [apalladi/feature-selection-adding-noise#6]
I tested the repo in a real world scenario and found it to be a very useful approach. I think that adding the option to choose between model features importance and average absolute SHAP value could be integrated as a parameter in the main function. If you believe this could be a valuable addition, I am willing to start working on it.

**Comment by apalladi** [comment]
Yes, this is currently one of the main issue and I could not find a nice solution up to now to generalize the way in which the feature importance is retrieved. As you have seen, I am using "hasattr" to check is coef_ or .feature_importances_ are available. If you have a better solution in mind, please go ahead and I will be happy to review your eventual pull request.
