### ISSUE TITLE
creation python library

### ISSUE THREAD

**Issue by valots12** [apalladi/feature-selection-adding-noise#7]
Given that the methodology will likely be used in Jupyter notebooks, as shown in the example, creating a Python library would enhance the usability of the repository. If you think this would be a valuable addition, I am willing to start working on it

**Comment by apalladi** [comment]
Hi, yes I agree with you and this was the idea of collecting all the functions in various scripts, in the folder that I called src. Feel free to expand your idea and, if you want, you can open a pull request once your version is ready.
